[2024-01-14T18:47:25.233+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags
[2024-01-14T18:47:25.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags for tasks to queue
[2024-01-14T18:47:25.234+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:47:25.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags
[2024-01-14T18:47:25.242+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:47:25.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags", line 6, in <module>
    import Python_TFT_project
ModuleNotFoundError: No module named 'Python_TFT_project'
[2024-01-14T18:47:25.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags
[2024-01-14T18:47:25.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags took 0.030 seconds
[2024-01-14T18:47:55.423+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags
[2024-01-14T18:47:55.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags for tasks to queue
[2024-01-14T18:47:55.424+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:47:55.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags
[2024-01-14T18:47:55.433+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:47:55.432+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags", line 6, in <module>
    import Python_TFT_project
ModuleNotFoundError: No module named 'Python_TFT_project'
[2024-01-14T18:47:55.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags
[2024-01-14T18:47:55.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags took 0.028 seconds
[2024-01-14T18:48:25.606+0000] {processor.py:161} INFO - Started process (PID=325) to work on /opt/airflow/dags
[2024-01-14T18:48:25.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags for tasks to queue
[2024-01-14T18:48:25.607+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:48:25.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags
[2024-01-14T18:48:25.615+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:48:25.614+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags", line 6, in <module>
    import Python_TFT_project
ModuleNotFoundError: No module named 'Python_TFT_project'
[2024-01-14T18:48:25.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags
[2024-01-14T18:48:25.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags took 0.028 seconds
[2024-01-14T18:48:55.784+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags
[2024-01-14T18:48:55.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags for tasks to queue
[2024-01-14T18:48:55.785+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:48:55.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags
[2024-01-14T18:48:55.793+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:48:55.792+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags", line 6, in <module>
    import Python_TFT_project
ModuleNotFoundError: No module named 'Python_TFT_project'
[2024-01-14T18:48:55.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags
[2024-01-14T18:48:55.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags took 0.037 seconds
