[2024-01-14T18:50:03.460+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_test.py
[2024-01-14T18:50:03.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2024-01-14T18:50:03.461+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:50:03.461+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2024-01-14T18:50:03.468+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:50:03.467+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 2, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-01-14T18:50:03.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2024-01-14T18:50:03.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.028 seconds
[2024-01-14T18:50:33.651+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_test.py
[2024-01-14T18:50:33.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2024-01-14T18:50:33.652+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:50:33.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2024-01-14T18:50:33.659+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:50:33.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 2, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-01-14T18:50:33.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2024-01-14T18:50:33.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.028 seconds
[2024-01-14T18:51:03.837+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/dag_test.py
[2024-01-14T18:51:03.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2024-01-14T18:51:03.838+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:51:03.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2024-01-14T18:51:03.845+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:51:03.843+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 2, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-01-14T18:51:03.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2024-01-14T18:51:03.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.035 seconds
[2024-01-14T18:51:34.013+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/dag_test.py
[2024-01-14T18:51:34.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test.py for tasks to queue
[2024-01-14T18:51:34.014+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:51:34.014+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test.py
[2024-01-14T18:51:34.019+0000] {logging_mixin.py:188} INFO - [2024-01-14T18:51:34.018+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test.py", line 2, in <module>
    from airflow.operators.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.PythonOperator'
[2024-01-14T18:51:34.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test.py
[2024-01-14T18:51:34.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test.py took 0.035 seconds
